# datAcron Ontology Traversals

This Jupyter NB serves as validation for the example queries and additionally as navigation and exploration notebook for the datAcron triple store. Where data is saved to CSVs, these CSV files are available in the data/ folder. The tutorial queries are sourced from: 
  1. "SPARQL_queries_example.pdf"
  2. http://ai-group.ds.unipi.gr/datacron_ontology/
  3. Mail by Giorgos Santipantakis with comments to 1.

This notebook replicates and extends the given example queries. The main concepts and properties of the datAcron ontology are depicted in the figure below.

![The datAcron ontology](images/schema_poster.svg)

### Definition of a query function

The query function is defined in the custom TripleStoreConnectorClass in datacron_connector.py. It allows to easily query both endpoints:
 - http://83.212.239.107:8890/sparql : short 107
 - http://83.212.239.109:3434/sparql : short 109

In [1]:
import pandas as pd
from pandas.io.json import json_normalize, read_json
from SPARQLWrapper import SPARQLWrapper, JSON, XML, RDF
from datacron_connector import TripleStoreConnector

#create two connector objects: one for 107 and one for 109 endpoints.
ts107 = TripleStoreConnector(0)
ts109 = TripleStoreConnector(1)

### Pull all concepts (ref: Page 1 + Giorgos comments)

The first query returns all concepts, for which at least one assertion exists in the triple. By recommendation of Giorgios, this query is preferred:

In [5]:
qry = """
PREFIX : <http://www.datacron-project.eu/datAcron#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?Concept
WHERE{
    ?Concept a owl:Class
     }
"""

df = ts107.query(qry)
df = ts107.clean(df)
df.head(5)

                Concept
0                 Thing
1               Nothing
2  AntiPollution_Vessel
3          DepartureLeg
4              ATSRoute

### Pull all properties

This query gets all properties, for which at least one instance exists in this graph.
(query improved by Giorgios).

I query both endpoints and compare results to get the properties that are only available in the 107 store.

In [21]:
qry = """
PREFIX owl: <http://www.w3.org/2002/07/owl#>
SELECT DISTINCT ?property 
WHERE {
    {?property a owl:ObjectProperty} UNION { ?Property a owl:DataProperty}
} ORDER BY ?property
"""

#Lets pull the properties from both endpoints and compare differences.
df1 = ts107.clean(ts107.query(qry))
df2 = ts109.clean(ts109.query(qry))
df3 = df1.merge(df2, how='outer', indicator=True).query('_merge == "left_only"')
df3

                                              property     _merge
168            http://www.w3.org/ns/ssn/attachedSystem  left_only
169        http://www.w3.org/ns/ssn/deployedOnPlatform  left_only
170            http://www.w3.org/ns/ssn/deployedSystem  left_only
171     http://www.w3.org/ns/ssn/deploymentProcessPart  left_only
172                   http://www.w3.org/ns/ssn/detects  left_only
173                   http://www.w3.org/ns/ssn/endTime  left_only
174         http://www.w3.org/ns/ssn/featureOfInterest  left_only
175               http://www.w3.org/ns/ssn/forProperty  left_only
176             http://www.w3.org/ns/ssn/hasDeployment  left_only
177                  http://www.w3.org/ns/ssn/hasInput  left_only
178  http://www.w3.org/ns/ssn/hasMeasurementCapability  left_only
179    http://www.w3.org/ns/ssn/hasMeasurementProperty  left_only
180      http://www.w3.org/ns/ssn/hasOperatingProperty  left_only
181         http://www.w3.org/ns/ssn/hasOperatingRange  left_only
182                 http://www.w3.org/ns/ssn/hasOutput  left_only
183               http://www.w3.org/ns/ssn/hasProperty  left_only
184              http://www.w3.org/ns/ssn/hasSubSystem  left_only
185       http://www.w3.org/ns/ssn/hasSurvivalProperty  left_only
186          http://www.w3.org/ns/ssn/hasSurvivalRange  left_only
187                  http://www.w3.org/ns/ssn/hasValue  left_only
188             http://www.w3.org/ns/ssn/implementedBy  left_only
189                http://www.w3.org/ns/ssn/implements  left_only
190               http://www.w3.org/ns/ssn/inCondition  left_only
191              http://www.w3.org/ns/ssn/inDeployment  left_only
192              http://www.w3.org/ns/ssn/isProducedBy  left_only
193              http://www.w3.org/ns/ssn/isPropertyOf  left_only
194                http://www.w3.org/ns/ssn/isProxyFor  left_only
195           http://www.w3.org/ns/ssn/madeObservation  left_only
196         http://www.w3.org/ns/ssn/observationResult  left_only
197     http://www.w3.org/ns/ssn/observationResultTime  left_only
198   http://www.w3.org/ns/ssn/observationSamplingTime  left_only
199                http://www.w3.org/ns/ssn/observedBy  left_only
200          http://www.w3.org/ns/ssn/observedProperty  left_only
201                  http://www.w3.org/ns/ssn/observes  left_only
202                 http://www.w3.org/ns/ssn/ofFeature  left_only
203                http://www.w3.org/ns/ssn/onPlatform  left_only
204      http://www.w3.org/ns/ssn/qualityOfObservation  left_only
205         http://www.w3.org/ns/ssn/sensingMethodUsed  left_only
206                 http://www.w3.org/ns/ssn/startTime  left_only

### Get more information on something (own work)

I am using property paths here to drill through the ontology graph. This seems to work fine with different Classes of the ontology.

In [22]:
qry = """
PREFIX : <http://www.datacron-project.eu/datAcron#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>

SELECT ?s
WHERE {
  ?s rdfs:subClassOf* :Trajectory .
}
"""
 #?s rdf:type/rdfs:subClassOf* :SpatiotemporalRegion 

df = ts107.query(qry)
df = ts107.clean(df)
df.head(10)

                         s
0               Trajectory
1      SyntheticTrajectory
2         ActualTrajectory
3       IntentedTrajectory
4      RegulatedTrajectory
5  FM_FlightPlanTrajectory
6           OpenTrajectory
7         ClosedTrajectory

For a class or instance of interest, we can use the DESCRIBE syntax to get some more information.

In [73]:
qry = """
PREFIX : <http://www.datacron-project.eu/datAcron#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>

DESCRIBE ?s
WHERE {
  ?s rdfs:subClassOf* :Trajectory .
}
"""
 #?s rdf:type/rdfs:subClassOf* :SpatiotemporalRegion 

df = ts107.query(qry)
df = ts107.clean(df)
df.head(10)

,s,p,o
0,RegulatedTrajectory,comment,A trajectory that has been regulated
1,FM_FlightPlanTrajectory,comment,"A sub-class of intented trajectory, which is r..."
2,hasPart,domain,Trajectory
3,ClosedTrajectory,subClassOf,ActualTrajectory
4,ClosedTrajectory,comment,A Trajectory where the destination is reached
5,Trajectory,comment,A trajectory consists of a sequence of tempor...
6,OpenTrajectory,type,http://www.w3.org/2002/07/owl#Class
7,departureOfTrajectory,domain,Trajectory
8,Trajectory,http://purl.org/dc/elements/1.1/creator,datAcron-project
9,Trajectory,type,http://www.w3.org/2002/07/owl#Class

Giorgos recommends also this syntax below and also rdfs:seeAlso

In [35]:
qry = """
PREFIX : <http://www.datacron-project.eu/datAcron#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>

DESCRIBE ?s
WHERE {
  ?s rdfs:isDefinedBy* :Trajectory .
}
"""
 #?s rdf:type/rdfs:subClassOf* :SpatiotemporalRegion 

df = ts107.query(qry)
df = ts107.clean(df)
df.head(10)

,s,p,o
0,hasPart,domain,Trajectory
1,Trajectory,comment,A trajectory consists of a sequence of tempor...
2,Trajectory,type,Class
3,departureOfTrajectory,domain,Trajectory
4,Trajectory,http://purl.org/dc/elements/1.1/creator,datAcron-project
5,destinationOfTrajectory,domain,Trajectory
6,IntentedTrajectory,subClassOf,Trajectory
7,RegulatedTrajectory,subClassOf,Trajectory
8,ActualTrajectory,subClassOf,Trajectory
9,SyntheticTrajectory,subClassOf,Trajectory

### Pull sector configs, affected airspaces, time periods and capacities (Page 2)

This query pulls some sector configurations which were selected in the past. For these configurations, it lists 10 affected airspaces, their period of effectivity and the defined capacity.

In [195]:
qry = """
PREFIX : <http://www.datacron-project.eu/datAcron#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>

SELECT ?config ?airspace ?capacity ?start ?end
WHERE {
  ?config a :FM_Configuration ;
          :hasCapacity ?capacity ;
          :configurationOfAirspace ?airspace ;
          dul:hasConstituent/:TimeStart ?start ;
          dul:hasConstituent/:TimeEnd ?end.
}
ORDER BY ?start
LIMIT 10
"""

df = ts107.query(qry)
df = ts107.clean(df)
df.to_csv('data/configs_and_affected_airspaces1.csv')
df.head(5)

,config,airspace,capacity,start,end
0,AirspaceConfiguration_LFMMXCTA_CF1_411,Airspace_LFMMXCTA_411,999,2016-03-31T00:00:00,2016-04-01T23:59:00
1,AirspaceConfiguration_LFMMXCTA_CF1_411,Airspace_LFMMXCTA_411,999,2016-03-31T00:00:00,2016-04-02T23:59:00
2,AirspaceConfiguration_LFMMXCTA_CF1_411,Airspace_LFMMXCTA_411,999,2016-03-31T00:00:00,2016-04-03T23:59:00
3,AirspaceConfiguration_LFMMXCTA_CF1_411,Airspace_LFMMXCTA_411,999,2016-03-31T00:00:00,2016-04-04T23:59:00
4,AirspaceConfiguration_LFMMXCTA_CF1_411,Airspace_LFMMXCTA_411,999,2016-03-31T00:00:00,2016-04-05T23:59:00

### Configurations and their sectors (own work)

If we want to know which configuration ever affected which sector, we can alter the above query: we omit the timestamp and select only DISTINCT values.

In [197]:
qry = """
PREFIX : <http://www.datacron-project.eu/datAcron#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>

SELECT DISTINCT * 
WHERE {
  ?config a :FM_Configuration ;
          :hasCapacity ?capacity ;
          :configurationOfAirspace ?airspace .
}
LIMIT 25000
"""

df = ts107.query(qry)
df = ts107.clean(df)
%time df = df.sort_values('airspace')
df.to_csv('data/configs_and_affected_airspaces2.csv')
df.head(5)

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 1.94 ms

                                     config capacity               airspace
0   AirspaceConfiguration_BIRDCTA_CONF1_411      999   Airspace_BIRDCTA_411
1   AirspaceConfiguration_BIRDICTA_CNF1_411      999  Airspace_BIRDICTA_411
2  AirspaceConfiguration_BIRDTOCA_CONF1_411      999  Airspace_BIRDTOCA_411
3   AirspaceConfiguration_DAAACTA_CONF1_411      999   Airspace_DAAACTA_411
4   AirspaceConfiguration_DAAATCTA_CNF1_411      999  Airspace_DAAATCTA_411

RESULT: Technical result: to avoid timeouts, it is better to pull the data first and let Pandas do the sorting. If I include an ORDER BY clause, the query will timeout. Instead, I use ```pandas df.sort_values()``` method. According to Giorgos comment, the same query should work with "ORDER BY" for the 109 endpoint, which I could confirm below:

In [23]:
qry = """
PREFIX : <http://www.datacron-project.eu/datAcron#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>

SELECT DISTINCT * 
WHERE {
  ?config a :FM_Configuration ;
          :hasCapacity ?capacity ;
          :configurationOfAirspace ?airspace .
} ORDER BY ?capacity
"""

df = ts107.query(qry)
df = ts107.clean(df)
df.to_csv('data/configs_and_affected_airspaces3_109.csv')
df.head(5)

                                    config capacity               airspace
0  AirspaceConfiguration_HECCCTA_CONF1_411        0   Airspace_HECCCTA_411
1   AirspaceConfiguration_EDWWCTAE_E8B_411       10  Airspace_EDWWCTAE_411
2   AirspaceConfiguration_EDWWCTAE_E9A_411       10  Airspace_EDWWCTAE_411
3   AirspaceConfiguration_EDWWCTAS_S2A_411       12  Airspace_EDWWCTAS_411
4  AirspaceConfiguration_LAAACTA_CONF2_411       13   Airspace_LAAACTA_411

### Pull airspaces with capacity != 999 (Page 2)

The following query pulls only those configurations, where a capacity number != 999 was set, by using a FILTER operator.

In [200]:
qry = """
PREFIX : <http://www.datacron-project.eu/datAcron#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>

SELECT * 
WHERE {
   ?c a :FM_Configuration ;
      :hasCapacity ?capacity ;
      :configurationOfAirspace ?airspace ;
      dul:hasConstituent/:TimeStart ?start ;
      dul:hasConstituent/:TimeEnd ?end.
   FILTER(?capacity !='999')
}
"""

df = ts107.query(qry)
df = ts107.clean(df)
df = df.sort_values('airspace')
df.to_csv('data/capacity_limited_configs.csv')
df.head(5)

,c,capacity,airspace,start,end
993,AirspaceConfiguration_EBBUCTA_CE2W2L_411,38,Airspace_EBBUCTA_411,2016-04-19T08:00:00,2016-04-19T06:59:00
973,AirspaceConfiguration_EBBUCTA_CE2W2L_411,38,Airspace_EBBUCTA_411,2016-04-13T08:00:00,2016-04-19T08:59:00
974,AirspaceConfiguration_EBBUCTA_CE2W2L_411,38,Airspace_EBBUCTA_411,2016-04-13T08:00:00,2016-04-19T08:59:00
975,AirspaceConfiguration_EBBUCTA_CE2W2L_411,38,Airspace_EBBUCTA_411,2016-04-13T08:00:00,2016-04-19T08:59:00
977,AirspaceConfiguration_EBBUCTA_CE2W2L_411,38,Airspace_EBBUCTA_411,2016-04-19T04:40:00,2016-04-13T08:59:00

### Configs and airspaces with limited capacity: only DISCTINCT values (own work)

I want to know if there is a direct relation between a configuration ID and the resulting airspace capacity. If this is the case, then the following query should only return one row per configuration ID.

In [202]:
qry = """
PREFIX : <http://www.datacron-project.eu/datAcron#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>

SELECT DISTINCT * 
WHERE {
   ?config a :FM_Configuration ;
           :hasCapacity ?capacity ;
           :configurationOfAirspace ?airspace .
   FILTER(?capacity !='999')
}
"""

df = ts107.query(qry)
df = ts107.clean(df)
df.to_csv('data/capacity_limited_configs2.csv')
df.iloc[9:14]

                                    config capacity               airspace
9   AirspaceConfiguration_EDWWCTAE_E6C_411       30  Airspace_EDWWCTAE_411
10  AirspaceConfiguration_EDWWCTAE_E7A_411       15  Airspace_EDWWCTAE_411
11  AirspaceConfiguration_EDWWCTAE_E7A_411       30  Airspace_EDWWCTAE_411
12  AirspaceConfiguration_EDWWCTAE_E8A_411       15  Airspace_EDWWCTAE_411
13  AirspaceConfiguration_EDWWCTAE_E8A_411       30  Airspace_EDWWCTAE_411

RESULT SEMANTICAL: as we can see with airspace configuration AirspaceConfiguration_EDWWCTAE_E7A_411 (EDWW is Bremen Radar), there are two different capacities for a single configuration. Therefore, the assumption that a direct dependency from configuration --> capacity exists, does not hold. 

It has to be noted though, that, looking at spanish sector configs, I could not find duplicate entries. TODO let Jose Manuel confirm that.

Giorgios recommended the following query, where we can see that there a couple of configurations where the capacity was not unique:

In [36]:
qry = """
PREFIX : <http://www.datacron-project.eu/datAcron#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>

PREFIX : <http://www.datacron-project.eu/datAcron#>
SELECT ?config (COUNT(?capacity) as ?count)
WHERE {
  ?config a :FM_Configuration ;
          :hasCapacity ?capacity .
}
GROUP BY ?config
ORDER BY DESC(?count)

"""

df = ts107.query(qry)
df = ts107.clean(df)
df.to_csv('data/capacity_limited_configs3.csv')
df.head(20)

                                      config count
0      AirspaceConfiguration_LFSBTMA_ALL_411     6
1      AirspaceConfiguration_LSAZUTA_1UA_411     6
2      AirspaceConfiguration_LSAZUTA_2UA_411     6
3      AirspaceConfiguration_LSAZUTA_3UC_411     6
4      AirspaceConfiguration_LSAZUTA_5UA_411     6
5      AirspaceConfiguration_LSAZUTA_4UA_411     6
6      AirspaceConfiguration_LSAZUTA_4UB_411     6
7      AirspaceConfiguration_LSAZUTA_2UB_411     6
8      AirspaceConfiguration_LSAZUTA_3UA_411     6
9     AirspaceConfiguration_EDWWCTAE_E8A_411     4
10    AirspaceConfiguration_EDWWCTAS_S2A_411     4
11  AirspaceConfiguration_UKOV2CTA_CONF4_411     4
12   AirspaceConfiguration_EDGGCTA7_C7_1_411     4
13    AirspaceConfiguration_EDWWCTAE_E7A_411     4
14  AirspaceConfiguration_EIDWCTA_CONF2A_411     4
15  AirspaceConfiguration_EIDWCTA_CONF4A_411     4
16   AirspaceConfiguration_LGGGCTA_CNF1A_411     2
17   AirspaceConfiguration_LGGGCTA_CNF2A_411     2
18   AirspaceConfiguration_LGGGCTA_CNF4A_411     2
19   AirspaceConfiguration_LGGGCTA_CNF5A_411     2

### Restricting the sector configuration query to a specific airspace (Page 3 + Giorgos comments)

PROBLEM (see Giorgos' comment below)

The following query pulls all configurations that belong to the Airspace Airspace_LSAGCTA (Geneva Control Area). Unfortunately, it returns more than 10000 results, most of them are illogical, because the airspace is configured several times at the same time, which semantically makes no sense according to my understanding of the ATC environment.

In [74]:
qry = """
PREFIX : <http://www.datacron-project.eu/datAcron#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>

SELECT * 
WHERE {
  ?config a :FM_Configuration ;
          :hasCapacity ?capacity ;
          :configurationOfAirspace  :Airspace_LSAGCTA_411 ;
          dul:hasConstituent/:TimeStart ?start ;
          dul:hasConstituent/:TimeEnd ?end.
}
"""

df = ts107.query(qry)
df = ts107.clean(df)
df = df.sort_values('start')
df.to_csv('data/configs_of_geneva.csv')
len(df)

10000

In [36]:
df.head(10)

,config,capacity,start,end
0,AirspaceConfiguration_LSAGCTA_I1A_411,40,2016-04-01T00:00:00,2016-04-01T03:54:00
565,AirspaceConfiguration_LSAGCTA_I1A_411,40,2016-04-01T00:00:00,2016-04-18T10:44:00
566,AirspaceConfiguration_LSAGCTA_I1A_411,40,2016-04-01T00:00:00,2016-04-18T10:49:00
567,AirspaceConfiguration_LSAGCTA_I1A_411,40,2016-04-01T00:00:00,2016-04-18T10:55:00
568,AirspaceConfiguration_LSAGCTA_I1A_411,40,2016-04-01T00:00:00,2016-04-18T10:59:00
569,AirspaceConfiguration_LSAGCTA_I1A_411,40,2016-04-01T00:00:00,2016-04-18T11:04:00
570,AirspaceConfiguration_LSAGCTA_I1A_411,40,2016-04-01T00:00:00,2016-04-18T14:51:00
571,AirspaceConfiguration_LSAGCTA_I1A_411,40,2016-04-01T00:00:00,2016-04-18T14:54:00
572,AirspaceConfiguration_LSAGCTA_I1A_411,40,2016-04-01T00:00:00,2016-04-18T15:09:00
573,AirspaceConfiguration_LSAGCTA_I1A_411,40,2016-04-01T00:00:00,2016-04-18T15:14:00

PROBLEM:

Instead of 2049 results as according to the tutorial, I get over 10000 configurations for the Geneva airspace?  And they all overlap in time?


NOTE
The syntactic subtlety: obviously, 'Airspace_LSAGCTA_411' is not the name but the ID of the Airspace in the triple store. Therefore, we do not need to search for a name and then combine the queries; it is sufficent to enter the Id directly with the ":" syntax. 


Giorgios' comments:

The following query checks how often the sectors were opened and closed:

In [43]:
qry = """
PREFIX : <http://www.datacron-project.eu/datAcron#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>
SELECT ?config (COUNT(?start) as ?count)
WHERE {
  ?config a :FM_Configuration ;
          :hasCapacity ?capacity ;
          :configurationOfAirspace :Airspace_LSAGCTA_411 ;
          dul:hasConstituent/:TimeStart ?start ;
          dul:hasConstituent/:TimeEnd ?end.
}
GROUP BY ?config
"""

df = ts107.query(qry)
df = ts107.clean(df)
df.to_csv('data/configs_of_geneva2.csv')
df.head(10)

                                  config    count
0  AirspaceConfiguration_LSAGCTA_I1A_411  2937796
1  AirspaceConfiguration_LSAGCTA_I3A_411    26244
2  AirspaceConfiguration_LSAGCTA_I2A_411    54756
3  AirspaceConfiguration_LSAGCTA_I2B_411  3175524

... "this made me check the raw data and I noticed that some cases "open" and "close" multiple times in the same day, e.g. you can find:

`
...
./OpeningScheme.cos:19/04/2016;LSAGCTA;05:05;05:19;I2B;T
./OpeningScheme.cos:19/04/2016;LSAGCTA;05:20;05:24;I2B;T
./OpeningScheme.cos:19/04/2016;LSAGCTA;05:25;05:36;I2B;T
...
`

The reason and semantics of these cases is not obvious to me either, and it is quite peculiar. We could also ask about it Jose Manuel."


This is a TODO Item --> Jörg

### Further inspect a specific airspace: drilling down to the airblocks (own work)


Comment by Giorgos: please consider using the 109 endpoint for this, as the 107 is not able to deserialize geometries to WKT.

By traversing the ontology, we should be able to drill down to the airblocks and get their properties.
The query below shows us that our airspace of interest, Airspace_LSAGCTA_411 consist of three sub-airspaces: Airspace_LSAGE_411, Airspace_LSAGN_411, Airspace_LSAGS_411.

RESULT SEMANTICAL:

LSAGN is Geneva North, LSAGE is Geneva East and LSAGS is Geneva South. The appendix _411 refers to the AIRAC cycle of this airspace. Reminder: the shape of an airspace may change at the change of an airac cycle. Therefore, the design decision to add the appendix _411 directly to the name of the airspace guarantees that there should be only one geometry per airspace ID.

In [24]:
qry = """
PREFIX : <http://www.datacron-project.eu/datAcron#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>

SELECT ?p ?o
WHERE {
  :Airspace_LSAGCTA_411 ?p ?o .
}
LIMIT 2000
"""

df = ts109.query(qry)
df = ts109.clean(df)
df.to_csv('data/airspace_properties.csv')
df.head(10)

         p                   o
0     type         FM_Airspace
1  hasPart  Airspace_LSAGE_411
2  hasPart  Airspace_LSAGN_411
3  hasPart  Airspace_LSAGS_411

Lets inspect these sub-airspaces further. The following query on 107 will return wrong airblock strings in form of `Airblock_LSAGE_LSAGE_301LS_75_245_75_245`, where the height level 75_245 is attached twice to the name. According Giorgos, I should use the 109 store until the 107 store is cleared of these obsolete triples. Below, I query both endpoints for documentation purposes.

In [61]:
qry = """
PREFIX : <http://www.datacron-project.eu/datAcron#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>

SELECT  ?s ?p ?o
WHERE { 
  VALUES ?s { :Airspace_LSAGE_411 :Airspace_LSAGN_411 :Airspace_LSAGS_411}
  VALUES ?p { dul:hasPart}
  ?s dul:hasPart ?o. 
}

LIMIT 2000
"""

# to check spanish airspace blocks, give values :Airspace_LECMASU_411 
#              :Airspace_LECMBLL_411 :Airspace_LECMBLU_411 
#              :Airspace_LECMCJL_411 :Airspace_LECMCJU_411 :Airspace_LECMDGL_411
#              :Airspace_LECMDGU_411 :Airspace_LECMPAL_411

blocks107 = ts107.query(qry)
blocks107 = ts107.clean(blocks107)
blocks107.to_csv('data/airspace_inspection.csv')

print(blocks107.head(10))
print(" ")

blocks109 = ts109.query(qry)
blocks109 = ts109.clean(blocks109)
blocks109.to_csv('data/airspace_inspection.csv')

print(blocks109.head(10))

                    s        p                                           o
0  Airspace_LSAGE_411  hasPart    Airblock_LSAGE_LSAGE_301LS_75_245_75_245
1  Airspace_LSAGE_411  hasPart    Airblock_LSAGE_LSAGE_311LS_75_245_75_245
2  Airspace_LSAGE_411  hasPart  Airblock_LSAGE_LSAGE_503LS_155_245_155_245
3  Airspace_LSAGE_411  hasPart  Airblock_LSAGE_LSAGE_513LS_155_245_155_245
4  Airspace_LSAGE_411  hasPart  Airblock_LSAGE_LSAGE_716LF_155_245_155_245
5  Airspace_LSAGE_411  hasPart    Airblock_LSAGE_LSAGE_750LS_75_245_75_245
6  Airspace_LSAGE_411  hasPart    Airblock_LSAGE_LSAGE_778LS_75_245_75_245
7  Airspace_LSAGE_411  hasPart  Airblock_LSAGE_LSAGE_802LS_130_245_130_245
8  Airspace_LSAGE_411  hasPart     Airblock_LSAGE_LSAGE_804LS_75_245_75_24
9  Airspace_LSAGN_411  hasPart  Airblock_LSAGN_LSAGN_080LF_155_195_155_195

                    s        p                     o
0  Airspace_LSAGE_411  hasPart  Airblock_LSAGE_301LS
1  Airspace_LSAGE_411  hasPart  Airblock_LSAGE_311LS
2  Airspace_LSAGE_411  hasPart  Airblock_LSAGE_503LS
3  Airspace_LSAGE_411  hasPart  Airblock_LSAGE_513LS
4  Airspace_LSAGE_411  hasPart  Airblock_LSAGE_716LF
5  Airspace_LSAGE_411  hasPart  Airblock_LSAGE_750LS
6  Airspace_LSAGE_411  hasPart  Airblock_LSAGE_778LS
7  Airspace_LSAGE_411  hasPart  Airblock_LSAGE_802LS
8  Airspace_LSAGE_411  hasPart   Airblock_LSAGE_804L
9  Airspace_LSAGN_411  hasPart  Airblock_LSAGN_080LF

RESULT TECHNICAL

As Giorgos suggested, the 109 store returns nicer Airblock strings. TODO recheck this query on 107 in the future to check if problems are fixed.

RESULT SEMANTICAL

The sub-Airspaces consist of airblocks. It should be possible to inspect these airblocks in more detail. Lets first check which properties are available for the Class FM_Airblock.

In [27]:
qry = """ 
PREFIX : <http://www.datacron-project.eu/datAcron#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>

SELECT DISTINCT ?p WHERE { ?s rdf:type :FM_Airblock ;   ?p ?o .} LIMIT 100 """

df = ts107.query(qry)
ts107.clean(df)
df.head(10)

               p
0           type
1  hasLowerLevel
2  hasUpperLevel
3    hasGeometry

RESULT SEMANTICAL

OK, so the airblocks should, as described in ontology and tutorial, be comprised out of :hasLowerLevel, :hasUpperLevel and :hasGeometry. Lets try to get these properties for the airblocks of the three Geneva airspaces LSAGE LSAGN and LSAGS.
The following query implements Giorgos recommendation in comment 14, to get the coordinates of all relevant airblocks. It is to be noted that Giorgos recommended to use the 109 endpoint. The query has slightly been altered because I am quering for a list of airblocks and not a list of airspaces.

PROBLEM

Why does this query not work with the 107 endpoint?

In [62]:
# Construct the list of airblocks that are to be passed 
str = ''
for i in range(len(blocks109)):
    if blocks109.iloc[i]['p'] == 'hasPart':
        str = str +' :' + blocks109.iloc[i]['o']
str = str[1:]
        
# check the list
print(str[:300] + '...')

:Airblock_LSAGE_301LS :Airblock_LSAGE_311LS :Airblock_LSAGE_503LS :Airblock_LSAGE_513LS :Airblock_LSAGE_716LF :Airblock_LSAGE_750LS :Airblock_LSAGE_778LS :Airblock_LSAGE_802LS :Airblock_LSAGE_804L :Airblock_LSAGN_080LF :Airblock_LSAGN_507LS :Airblock_LSAGN_700LF :Airblock_LSAGN_701LF :Airblock_LSAGN...

In [78]:
qry = """
PREFIX : <http://www.datacron-project.eu/datAcron#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>
PREFIX myfn: <java:datAcronTester.unipi.gr.sparql_functions.>

SELECT  ?airspace ?lowerlevel ?upperlevel ?block ?geom ?wkt
WHERE { 
   VALUES ?block { """ +str + """}
   ?airspace dul:hasPart       ?block .
   ?block       :hasLowerLevel ?lowerlevel ;
                :hasUpperLevel ?upperlevel ;
                :hasGeometry ?geom.
   ?geom        :hasMBR_WKT  ?wkt .
    
}
"""

df2 = ts109.query(qry)
df2 = ts109.clean(df2)
df2.head(10)

,airspace,lowerlevel,upperlevel,block,geom,wkt
0,Airspace_LSAGE_411,2286.0,7467.6,Airblock_LSAGE_301LS,http://83.212.239.107/geometries/airblocks/301LS,"POLYGON ((6.39666666666667 46.6491666666667, 6..."
1,Airspace_LSAGE_411,2286.0,7467.6,Airblock_LSAGE_311LS,http://83.212.239.107/geometries/airblocks/311LS,"POLYGON ((6.68444444444444 46.2133333333333, 6..."
2,Airspace_LSAGE_411,4724.400000000001,7467.6,Airblock_LSAGE_503LS,http://83.212.239.107/geometries/airblocks/503LS,"POLYGON ((6.32888888888889 46.4380555555556, 6..."
3,Airspace_LSAGE_411,4724.400000000001,7467.6,Airblock_LSAGE_513LS,http://83.212.239.107/geometries/airblocks/513LS,"POLYGON ((6.40305555555556 46.3416666666667, 6..."
4,Airspace_LSAGE_411,4724.400000000001,7467.6,Airblock_LSAGE_716LF,http://83.212.239.107/geometries/airblocks/716LF,"POLYGON ((6.39166666666667 46.7433333333333, 6..."
5,Airspace_LSAGE_411,2286.0,7467.6,Airblock_LSAGE_750LS,http://83.212.239.107/geometries/airblocks/750LS,"POLYGON ((6.64166666666667 46.9808333333333, 6..."
6,Airspace_LSAGE_411,2286.0,7467.6,Airblock_LSAGE_778LS,http://83.212.239.107/geometries/airblocks/778LS,"POLYGON ((7.12305555555556 46.3925, 7.12305555..."
7,Airspace_LSAGE_411,3962.4,7467.6,Airblock_LSAGE_802LS,http://83.212.239.107/geometries/airblocks/802LS,"POLYGON ((7.20138888888889 46.1833333333333, 7..."
8,Airspace_LSAGN_411,4724.400000000001,5943.6,Airblock_LSAGN_080LF,http://83.212.239.107/geometries/airblocks/080LF,"POLYGON ((5.6 46.1166666666667, 5.6 46.5461111..."
9,Airspace_LSAGN_411,5943.6,7467.6,Airblock_LSAGN_507LS,http://83.212.239.107/geometries/airblocks/507LS,"POLYGON ((5.97222222222222 46.1433333333333, 5..."




The query below gives us all spanish airblocks with their coordinates, the airspace thy belong to and the super-airspace they might belong to.

In [80]:
qry = """
PREFIX : <http://www.datacron-project.eu/datAcron#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>
PREFIX myfn: <java:datAcronTester.unipi.gr.sparql_functions.>

SELECT  ?bigairspace ?airspace ?block ?wkt ?lowerlevel ?upperlevel 
WHERE { 
   
   ?airspace dul:hasPart       ?block .
   ?block       :hasLowerLevel ?lowerlevel ;
                :hasUpperLevel ?upperlevel ;
                :hasGeometry   ?geom.
   ?geom        :hasMBR_WKT  ?wkt .
   
   OPTIONAL {?bigairspace dul:hasPart ?airspace.}.
   
   FILTER regex(str(?block), 'Airblock_LE', "i") 
} LIMIT 1000
"""

df2 = ts109.query(qry)
df2 = ts109.clean(df2)
%time df2 = df2.sort_values('block')

df2.to_csv('data/allspanishairblocks.csv')
df2.head(10)

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 2.12 ms

,bigairspace,airspace,block,wkt,lowerlevel,upperlevel
0,Airspace_LETOT_411,Airspace_LEABTA_411,Airblock_LEABTA_249LE,"POLYGON ((-2.99166666666667 39, -2.99166666666...",0.0,7467.6
1,Airspace_LEABTMA_411,Airspace_LEABTA_411,Airblock_LEABTA_249LE,"POLYGON ((-2.99166666666667 39, -2.99166666666...",0.0,7467.6
2,Airspace_LETOT_411,Airspace_LEAMTA_411,Airblock_LEAMTA_650LE,"POLYGON ((-2.84083333333333 36.4166666666667, ...",0.0,4419.6
3,Airspace_LEAMTMA_411,Airspace_LEAMTA_411,Airblock_LEAMTA_650LE,"POLYGON ((-2.84083333333333 36.4166666666667, ...",0.0,4419.6
4,Airspace_LETOT_411,Airspace_LEAMTA_411,Airblock_LEAMTA_651LE,"POLYGON ((-1.83333333333333 36.85, -1.83333333...",0.0,4419.6
5,Airspace_LEAMTMA_411,Airspace_LEAMTA_411,Airblock_LEAMTA_651LE,"POLYGON ((-1.83333333333333 36.85, -1.83333333...",0.0,4419.6
6,Airspace_LETOT_411,Airspace_LEAMTA_411,Airblock_LEAMTA_652LE,"POLYGON ((-1.86111111111111 36.7138888888889, ...",0.0,4419.6
7,Airspace_LEAMTMA_411,Airspace_LEAMTA_411,Airblock_LEAMTA_652LE,"POLYGON ((-1.86111111111111 36.7138888888889, ...",0.0,4419.6
9,Airspace_LEAMTMA_411,Airspace_LEAMTA_411,Airblock_LEAMTA_653LE,"POLYGON ((-1.92361111111111 36.4530555555556, ...",0.0,4419.6
8,Airspace_LETOT_411,Airspace_LEAMTA_411,Airblock_LEAMTA_653LE,"POLYGON ((-1.92361111111111 36.4530555555556, ...",0.0,4419.6

### Get frequency of configurations applied (Page 3)

This query returns the number of configurations that have been applied to the sector which are available in the database.

In [77]:
qry = """ 
PREFIX : <http://www.datacron-project.eu/datAcron#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>

SELECT (COUNT(?x) as ?count) ?a
WHERE {
    ?x :configurationOfAirspace ?a ;
       :hasCapacity ?capacity .
    FILTER(?capacity != "999")
} 
GROUP BY ?a
ORDER BY DESC(?count)
"""
df = ts107.query(qry)
ts107.clean(df)
#df.to_csv("airspaceconfigs.csv")
df.head(10)

  count                      a
0    60   Airspace_LEMDTMA_411
1    60  Airspace_LFMMCTAW_411
2    50   Airspace_LSAZUTA_411
3    40  Airspace_LECMCTAN_411
4    28   Airspace_LYBACTA_411
5    26  Airspace_LECMCTAS_411
6    26   Airspace_LOVVCTA_411
7    20   Airspace_LEBLTMA_411
8    20   Airspace_LECPCTA_411
9    18   Airspace_LECSCTA_411

### Get all configurations in a specific time frame (Page 3)

The following query gets all configurations on 28th of April, 2016 etween 00:00 and 05:00 UTC. 

PROBLEM

The query according tutorial is malformed in two ways: 
1. The Airspace ID is Airspace_LSAGCTA_411, not Airspace_LSAGCTA (thanks to Christos for pointing this out) 
2. The result set for the given time frame is empty. If I alter the time frame to be from 27th of April, I get some (max 10.000) results. But 10.000 configurations for a 29 hour time period? This seems odd to me.
3. If I inspect the results (for example, take row 0), then I get configurations that started at the 27th of April, but ended at the 1st of April .... which is at least mind-bending.

ASSUMPTION:
With the query syntax like below, we are still OR-ing the restrictions of the results. Therefore, we get all configs that started after ?start or ended before ?end. Which are basically, all configurations.

In [197]:
qry = """ 
PREFIX : <http://www.datacron-project.eu/datAcron#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?config ?capacity
WHERE {
    ?config a :FM_Configuration;
            :hasCapacity ?capacity ;
            :configurationOfAirspace :Airspace_LSAGCTA_411 ;
            dul:hasConstituent/:TimeStart ?start ;
            dul:hasConstituent/:TimeEnd ?end .
    FILTER( str(?start)>"2016-04-28T00:00:00" && str(?end)<"2016-04-28T05:00:00" )
}

"""
df = ts107.query(qry)
ts107.clean(df)
df.to_csv("data/airspaceconfigs_0000_0500.csv")
df.head(5)

Empty DataFrame
Columns: [config, capacity]
Index: []

So, zero entries? This does not seem reasonable. So lets say that the string comparison of times gives odd results. Let's try this again with the xsd namespace like in the tutorial.

In [198]:
qry = """ 
PREFIX : <http://www.datacron-project.eu/datAcron#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?config ?capacity
WHERE {
    ?config a :FM_Configuration;
            :hasCapacity ?capacity ;
            :configurationOfAirspace :Airspace_LSAGCTA_411 ;
            dul:hasConstituent/:TimeStart ?start ;
            dul:hasConstituent/:TimeEnd ?end .
    FILTER( ?start > xsd:dateTime("2016-04-28 00:00:00") && ?end < xsd:dateTime("2016-04-28 05:00:00") )
}

"""
df = ts107.query(qry)
ts107.clean(df)
df.to_csv("data/airspaceconfigs_0000_0500.csv")
df.head(5)

Empty DataFrame
Columns: [config, capacity]
Index: []

Same odd results. If I now alter the time frame to 27th of April, I get the following, illogical results: more than 10.000 configurations applied within 29 hours for a single airspace .... seems odd to me.

In [192]:
qry = """ 
PREFIX : <http://www.datacron-project.eu/datAcron#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?config ?capacity ?start ?end
WHERE {
    ?config a :FM_Configuration;
            :hasCapacity ?capacity ;
            :configurationOfAirspace :Airspace_LSAGCTA_411 ;
            dul:hasConstituent/:TimeStart ?start ;
            dul:hasConstituent/:TimeEnd ?end .
    FILTER( ?start > xsd:dateTime("2016-04-27 00:00:00") && ?end < xsd:dateTime("2016-04-28 05:00:00") )
}

"""
df = ts107.query(qry)
ts107.clean(df)
df.to_csv("data/airspaceconfigs_0000_0500.csv")
len(df)

10000

## Trajectories Inspection (Page 3 bottom)

The following query pulls 100 trajectories out of the store, directly with their coordinates.

NOTE

Be aware that the direct availability of the coordinates is a convenience function created by the RDF maintainers. It prevents us from needing to traverse into every single semantic node of a tracjectory to get the coordinates and allows for easy plotting.

PROBLEM

Unfortunately, this convenience function only gives us 2D coordinates without altitude or time information. But what we need in order to cross trajectories and airblocks is the 4D coordinates including time and altitude. The chosen data format, well known text (WKT) would able to handle 4D coordinates, because z coordinate is available for altitude rep and m coordinate for linear data (time passed since epoch could be considered as a linear distance of a point from the epoch).

In [199]:
qry = """ 
PREFIX : <http://www.datacron-project.eu/datAcron#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>

SELECT DISTINCT * WHERE {
  ?flight_plan_ID a :FM_RTFM ;
                    :departureAirport ?dep ;
                    :destinationAirport ?dest ;
                    :reportsTrajectory ?trajectory_ID .
  ?trajectory_ID dul:hasConstituent/:hasWKT ?geom

} LIMIT 100

"""

#to query another endpoint, change the URL for the service and the query
df = ts107.query(qry)
ts107.clean(df)
df.to_csv("data/trajectories.csv")
df.head(5)

,flight_plan_ID,dep,dest,trajectory_ID,geom
0,flight_plan_AA51114077,Place_MontpellierMediterranee_Airport,Place_BastiaPoretta_Airport,traj_AA51114077_20160401003000,"LINESTRING(3.961389 43.583333, 3.968056 43.580..."
1,flight_plan_AA51114336,Place_Bristol___Lulsgate,Place_TenerifeSur_ReinaSofia_Airport,traj_AA51114336_20160331154500,"LINESTRING(-2.719167 51.382778, -2.736111 51.3..."
2,flight_plan_AA51114524,Place_Valencia_Manises_Airport,Place_Bucuresti_HenriCoanda_Airport,traj_AA51114524_20160331183000,"LINESTRING(-0.481667 39.489444, -0.492222 39.4..."
3,flight_plan_AA51115368,Place_Nantes_Atlantique_Airport,Place_London___Gatwick_Airport,traj_AA51115368_20160331155000,"LINESTRING(-1.607778 47.156944, -1.601389 47.1..."
4,flight_plan_AA51121974,Place_QuimperPluguffan_Airport,Place_ParisOrly_Airport,traj_AA51121974_20160401044000,"LINESTRING(-4.167778 47.975, -4.143056 47.9677..."

#### Visualizing the trajectories 

We can visualize these trajectories in 2D using gemoet [https://pypi.python.org/pypi/geomet/0.1.0] for  WKT-->GeoJson transformation and folium [https://github.com/python-visualization/folium], which is a python wrapper for Leaflet.js interactive maps.

In [200]:
from geomet import wkt
import json

#Convert WKT column into a gejson column
df["geojson"] = df["geom"].apply(lambda x: json.dumps(wkt.loads(x)))
df = df.drop('geom', 1)
df.head(5)

,flight_plan_ID,dep,dest,trajectory_ID,geojson
0,flight_plan_AA51114077,Place_MontpellierMediterranee_Airport,Place_BastiaPoretta_Airport,traj_AA51114077_20160401003000,"{""type"": ""LineString"", ""coordinates"": [[3.9613..."
1,flight_plan_AA51114336,Place_Bristol___Lulsgate,Place_TenerifeSur_ReinaSofia_Airport,traj_AA51114336_20160331154500,"{""type"": ""LineString"", ""coordinates"": [[-2.719..."
2,flight_plan_AA51114524,Place_Valencia_Manises_Airport,Place_Bucuresti_HenriCoanda_Airport,traj_AA51114524_20160331183000,"{""type"": ""LineString"", ""coordinates"": [[-0.481..."
3,flight_plan_AA51115368,Place_Nantes_Atlantique_Airport,Place_London___Gatwick_Airport,traj_AA51115368_20160331155000,"{""type"": ""LineString"", ""coordinates"": [[-1.607..."
4,flight_plan_AA51121974,Place_QuimperPluguffan_Airport,Place_ParisOrly_Airport,traj_AA51121974_20160401044000,"{""type"": ""LineString"", ""coordinates"": [[-4.167..."

In [201]:
#Lets inscpect how the geojson between Bristol and Tenerife looks like. 
df.iloc[1]['geojson']

'{"type": "LineString", "coordinates": [[-2.719167, 51.382778], [-2.736111, 51.382778], [-2.787222, 51.382222], [-2.838333, 51.381944], [-2.866389, 51.366111], [-2.894722, 51.350278], [-2.998056, 51.2925], [-3.359722, 51.178611], [-3.362778, 51.161111], [-3.371944, 51.108889], [-3.384167, 51.039167], [-3.388611, 51.013056], [-3.398056, 50.957778], [-3.416944, 50.8475], [-3.423889, 50.809167], [-3.431944, 50.761667], [-3.448333, 50.666667], [-3.4525, 50.641389], [-3.463889, 50.574167], [-3.473333, 50.518611], [-3.493611, 50.398611], [-3.495556, 50.362778], [-3.505278, 50.184167], [-3.517222, 49.960556], [-3.529444, 49.737222], [-3.558333, 49.658611], [-3.638611, 49.44], [-3.728333, 49.195278], [-3.783056, 49.046944], [-3.808611, 48.976944], [-4.061667, 48.301944], [-4.184722, 47.957222], [-4.3125, 47.829444], [-4.524722, 47.591389], [-4.990556, 47.079167], [-5.408056, 46.612778], [-6.919722, 44.835278], [-7.012778, 44.698056], [-7.143889, 44.504444], [-8.926667, 41.872778], [-9.016111, 41.667778], [-9.161389, 41.334444], [-10.234444, 38.873333], [-11.448333, 35.966667], [-12.911667, 34.261111], [-13.836111, 33.149444], [-15.301667, 31.300833], [-15.850278, 30.433889], [-16.372778, 29.591389], [-16.990556, 28.928056], [-17.023056, 28.893333], [-17.094444, 28.816389], [-17.211667, 28.690833], [-17.263611, 28.635], [-17.315556, 28.579167], [-17.374167, 28.516389], [-17.439167, 28.446389], [-17.452222, 28.4325], [-17.375278, 28.389444], [-17.29, 28.341667], [-17.196111, 28.289167], [-17.170556, 28.274722], [-17.115, 28.234444], [-17.027778, 28.170833], [-16.877222, 28.061389], [-16.773056, 28.028889], [-16.687778, 28.0025], [-16.676389, 28.006667], [-16.647222, 28.017222], [-16.622222, 28.026389], [-16.604167, 28.033056], [-16.5725, 28.044444]]}'

In [202]:
import folium


map1 = folium.Map(location=[40,10], zoom_start=4, control_scale=True, prefer_canvas=True)
for index, row in df.head(5).iterrows():
    c = folium.GeoJson(row['geojson'], name = (row['dep']+ row['dest']),overlay=True, 
                       style_function = lambda feature: {'fillColor': '#ffaf00','color': 'blue', 'weight': 2.5,'dashArray': '5, 5'},
                       highlight_function = lambda feature: {'fillColor': '#ffaf00','color': 'green', 'weight': 5,'dashArray': '5, 5'})
    c.add_child(folium.Popup(row['trajectory_ID'] + '\n' + row['dep'] +'\n' + row['dest']))
    c.add_to(map1)
folium.LayerControl().add_to(map1)
map1.save(outfile='maps/map1.html')

map1

### Further inspecting trajectories (Page 4 bottom)

According to the tutorial, the following query should give us all semantic nodes and their linked information.

PROBLEM

see below.

In [208]:
qry = """ 
PREFIX : <http://www.datacron-project.eu/datAcron#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>

SELECT ?node ?time ?position 
WHERE {
   :traj_AA51114077_20160401003000 :hasPart ?node .
   ?node dul:hasConstituent/:TimeStart ?time ;
         dul:hasConstituent/:hasWKT ?position ; 
         ?p ?o
} ORDER BY ?time

"""

#traj_AA51114077_20160401003000
#traj_AA51114077_20160401003000_m1  <---- according tutorial, we should use, but gives 0 results

tutorialtraj = ts107.query(qry)
ts107.clean(tutorialtraj)
tutorialtraj.to_csv("data/node.csv")
len(tutorialtraj)

3004

In [209]:
tutorialtraj.head(20)

,node,time,position
0,n_AA51114077_20160401003000_1,2016-04-01T03:52:30,POINT(3.961389 43.583333)
1,n_AA51114077_20160401003000_1,2016-04-01T03:52:30,POINT(3.961389 43.583333)
2,n_AA51114077_20160401003000_1,2016-04-01T03:52:30,POINT(3.961389 43.583333)
3,n_AA51114077_20160401003000_1,2016-04-01T03:52:30,POINT(3.961389 43.583333)
4,n_AA51114077_20160401003000_1,2016-04-01T03:52:30,POINT(3.961389 43.583333)
5,n_AA51114077_20160401003000_1,2016-04-01T03:52:30,POINT(3.961389 43.583333)
6,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(8.626944 43.118333)
7,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(8.626944 43.118333)
8,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(9.506944 42.661944)
9,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(9.506944 42.661944)
10,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(3.968056 43.580833)
11,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(3.968056 43.580833)
12,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(4.917222 43.34)
13,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(4.917222 43.34)
14,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(3.986389 43.575278)
15,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(3.986389 43.575278)
16,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(3.998333 43.5725)
17,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(3.998333 43.5725)
18,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(4.163333 43.530556)
19,n_AA51114077_20160401003000_2,2016-04-01T03:52:49,POINT(4.163333 43.530556)

PROBLEM 

This representation does not seem logical. How is it possible that one and the same node can have multiple timestamps and multiple positions? Is it even realistic that a flight has 3004 informations on semantic nodes? I do not think so. In fact, I do think that there is something wrong with how the data is queried or how it is stored in the data store. 



May be something is wrong with this trajectory,. Let me check another:

(Bristol-Teneriffa traj_AA51114336_20160331154500)
                   
Lets see what properties for a single node are available:

In [211]:
qry = """ 
PREFIX : <http://www.datacron-project.eu/datAcron#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>

SELECT DISTINCT ?p ?o 
WHERE {
    :n_AA51114336_20160331154500_1  ?p ?o
}

"""
node = ts107.query(qry)
ts107.clean(node)
node.to_csv("data/node.csv")
node

                p                              o
0  hasConstituent                   t_1459445125
1  hasConstituent                      geom_EGGD
2        precedes  n_AA51114336_20160331154500_2

Lets get all the data for the trajectory between Bristol and Tenerife (like the query from page 4). We would excpect that the reulsting nodes exaclty comprise the trajectory that was plotted above.

In [212]:
qry = """ 
PREFIX : <http://www.datacron-project.eu/datAcron#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>

SELECT *
WHERE {
    :traj_AA51114336_20160331154500 :hasPart ?node .
    ?node dul:hasConstituent/:TimeStart ?time ;
          dul:hasConstituent/:hasWKT ?position ;
          ?p ?o .      
}

"""

singletraj = ts107.query(qry)
ts107.clean(singletraj)
singletraj.to_csv("data/singletrajectory.csv")

len(singletraj)

10000

PROBLEM

The trajecotry consists of 10.000 nodes? This does not seem resonable to me. I will now try to get some better syntax into the query.

In [213]:
qry = """ 
PREFIX : <http://www.datacron-project.eu/datAcron#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>

SELECT *
WHERE {
    :traj_AA51114336_20160331154500 :hasPart ?node .
    ?node dul:hasConstituent/:TimeStart ?time .
    ?node dul:hasConstituent/:hasWKT ?position .      
}

"""

singletraj = ts107.query(qry)
ts107.clean(singletraj)
singletraj.to_csv("data/singletrajectory.csv")

len(singletraj)

3504

Now, the resultset is "only" 3504 nodes. Lets clean the rows a little bit and get only distinct node IDs:

In [214]:
singletraj = singletraj.drop_duplicates(subset = 'node', keep = 'first')

singletraj = singletraj.sort_values('node')
singletraj.to_csv("data/singletrajectory_drop_duplicates.csv")
print(len(singletraj))
singletraj.head(10)

72

,node,time,position
3476,n_AA51114336_20160331154500_1,2016-03-31T17:25:25,POINT(-2.719167 51.382778)
320,n_AA51114336_20160331154500_10,2016-03-31T17:32:59,POINT(-16.604167 28.033056)
400,n_AA51114336_20160331154500_11,2016-03-31T17:33:42,POINT(-16.604167 28.033056)
3448,n_AA51114336_20160331154500_12,2016-03-31T17:33:57,POINT(-3.388611 51.013056)
480,n_AA51114336_20160331154500_13,2016-03-31T17:34:28,POINT(-16.604167 28.033056)
3442,n_AA51114336_20160331154500_14,2016-03-31T17:35:26,POINT(-3.416944 50.8475)
3454,n_AA51114336_20160331154500_15,2016-03-31T17:35:50,POINT(-3.423889 50.809167)
560,n_AA51114336_20160331154500_16,2016-03-31T17:36:14,POINT(-16.604167 28.033056)
3452,n_AA51114336_20160331154500_17,2016-03-31T17:37:00,POINT(-3.448333 50.666667)
2720,n_AA51114336_20160331154500_18,2016-03-31T17:37:14,POINT(-16.604167 28.033056)

PROBLEM

Possible BUG? Lets inspect this result. If we check out the third line, we see a node at 17:33:42 at some coordinates -16°E, 28°N, which is close to Tenerife. At the fourth row, we see a node at 17:33:57, so only 15 seconds later. Magically, the airplace is now at position -3°E, 51°N, which is around Bristol. So the airplane did not only travel backwards, it also did this incredibly fast!   I suppose that there must be a problem with the data or the way I query this data.

See further below for a map with the malformed trajectory.

# UNDER CONSTRUCTION  





everything below is "under construction"

### Reconstructing trajectories from nodes (own work)


The final goal is to recosntruct the rajectories from the nodes, in order to have "enriched" trajectories with time, altitude and weather information. For this, we try to get all positions and times into one GeoJSON file which can then be passed to the folium map. According to their tutorial, the format of the GeoJSON is as follows:

```
{
"type": "Feature",
"geometry": {"type": "LineString", 
             "coordinates": [[lon, 25] for
                                lon in np.linspace(-150, 150, 25)] }, 
"properties": {"times": [1435708800000+i*86400000 for i in np.linspace(0, 25, 25)] }
}
```
So we need to create a dict which is formatted accordingly. The functions defined in the following box will help me with this task.

In [227]:
def wkt_to_geojson(dataframe, wkt_column_name, geojson_column_name):
    """
    Gets a pandas.DataFrame and converts a WKT column into a GeoJSON column.
    The GeoJSON column then contains a dict.
    
    Keyword arguments:
    dataframe -- the pandas.DataFrame which should be altered
    wkt_column_name -- the name of the column containing the well-known-text
    geojson_column_name -- how the GeoJSON column shall be named
    
    """
    if type(dataframe) != pd.core.frame.DataFrame:
        raise TypeError('The parameter dataframe must be a Pandas DataFrame.')
    if not wkt_column_name in dataframe.columns:
        raise ValueError('No column with the specified name found in the DataFrame')
    
    dataframe[geojson_column_name] = dataframe[wkt_column_name].apply(lambda x: wkt.loads(x))
    return dataframe


def inject_time(geojson, time):
    """
    Injects Time dimension into geoJSON coordinates. Expects  a dict in geojson POINT format.
    """
    #geojson['coordinates'] = [geojson['coordinates'][0], geojson['coordinates'][1], time]
    geojson['properties'] = {'times' : [time]}
    return geojson

def extract_coordinates(geojson):
    """
    Returns only the coordinates from a geoJSON POINT object
    """
    return geojson['coordinates']

In [226]:
#convert position to geoJson
singletraj = wkt_to_geojson(singletraj, 'position', 'geojson')
#pull only coordinates out of the GeoJSON column
singletraj['coord_only'] =  singletraj['geojson'].apply(lambda x: extract_coordinates(x))
singletraj = singletraj.drop('geojson', 1)
singletraj = singletraj.drop('position', 1)
singletraj.head(5)

NameError: name 'dataframe' is not defined

In [219]:
#convert time string into milliseconds since epoch. After this, we can sort the resulting DataFrame by time.
from datetime import datetime

singletraj['time'] = singletraj['time'].apply(lambda x: datetime.strptime(x, '%Y-%m-%dT%H:%M:%S').timestamp())
singletraj = singletraj.sort_values('time')

singletraj.to_csv('data/singletraj_timestamped.csv')
singletraj.head(10)

                                node          time               coord_only
3476   n_AA51114336_20160331154500_1  1.459438e+09   [-2.719167, 51.382778]
0      n_AA51114336_20160331154500_2  1.459438e+09  [-16.604167, 28.033056]
80     n_AA51114336_20160331154500_3  1.459438e+09  [-16.604167, 28.033056]
3456   n_AA51114336_20160331154500_4  1.459438e+09   [-2.838333, 51.381944]
160    n_AA51114336_20160331154500_5  1.459438e+09  [-16.604167, 28.033056]
240    n_AA51114336_20160331154500_6  1.459438e+09  [-16.604167, 28.033056]
3502   n_AA51114336_20160331154500_7  1.459438e+09     [-2.998056, 51.2925]
3446   n_AA51114336_20160331154500_8  1.459438e+09   [-3.359722, 51.178611]
1680   n_AA51114336_20160331154500_9  1.459438e+09  [-16.604167, 28.033056]
320   n_AA51114336_20160331154500_10  1.459438e+09  [-16.604167, 28.033056]

In [220]:
singletraj.head(5)

                               node          time               coord_only
3476  n_AA51114336_20160331154500_1  1.459438e+09   [-2.719167, 51.382778]
0     n_AA51114336_20160331154500_2  1.459438e+09  [-16.604167, 28.033056]
80    n_AA51114336_20160331154500_3  1.459438e+09  [-16.604167, 28.033056]
3456  n_AA51114336_20160331154500_4  1.459438e+09   [-2.838333, 51.381944]
160   n_AA51114336_20160331154500_5  1.459438e+09  [-16.604167, 28.033056]

Now we have the times and the coordinates in a dict-friendly way. We can now iterate through the rows and create our custom GeoJSON object, that we can then pass to the folium map.

In [228]:
#TODO use this function instead

def geojsonify(dataframe, time_column, coord_column):
    res = {}
    res['type'] = 'LineString'
    res['coordinates'] = []
    res['properties'] = {'times': []}

    for x in range(len(dataframe)):
        res['coordinates'].append(dataframe.iloc[x][coord_column])
        res['properties']['times'].append(dataframe.iloc[x][time_column])
    res2 = {}
    res2['type']  = 'Feature'
    res2['geometry'] = res
    return res2

In [221]:
ng = {}
ng['type'] = 'LineString'
ng['coordinates'] = []
ng['properties'] = {'times': []}

for x in range(len(singletraj)):
    ng['coordinates'].append(singletraj.iloc[x]['coord_only'])
    ng['properties']['times'].append(singletraj.iloc[x]['time'])

ng2 = {}
ng2['type']  = 'Feature'
ng2['geometry'] = ng

ng2

{'geometry': {'coordinates': [[-2.719167, 51.382778],
   [-16.604167, 28.033056],
   [-16.604167, 28.033056],
   [-2.838333, 51.381944],
   [-16.604167, 28.033056],
   [-16.604167, 28.033056],
   [-2.998056, 51.2925],
   [-3.359722, 51.178611],
   [-16.604167, 28.033056],
   [-16.604167, 28.033056],
   [-16.604167, 28.033056],
   [-3.388611, 51.013056],
   [-16.604167, 28.033056],
   [-3.416944, 50.8475],
   [-3.423889, 50.809167],
   [-16.604167, 28.033056],
   [-3.448333, 50.666667],
   [-16.604167, 28.033056],
   [-3.463889, 50.574167],
   [-16.604167, 28.033056],
   [-3.493611, 50.398611],
   [-16.604167, 28.033056],
   [-16.604167, 28.033056],
   [-16.604167, 28.033056],
   [-3.529444, 49.737222],
   [-16.604167, 28.033056],
   [-16.604167, 28.033056],
   [-16.604167, 28.033056],
   [-16.604167, 28.033056],
   [-3.808611, 48.976944],
   [-4.061667, 48.301944],
   [-4.184722, 47.957222],
   [-4.3125, 47.829444],
   [-4.524722, 47.591389],
   [-4.990556, 47.079167],
   [-5.408056, 46.612778],
   [-6.919722, 44.835278],
   [-16.604167, 28.033056],
   [-16.604167, 28.033056],
   [-8.926667, 41.872778],
   [-16.604167, 28.033056],
   [-16.604167, 28.033056],
   [-10.234444, 38.873333],
   [-11.448333, 35.966667],
   [-12.911667, 34.261111],
   [-13.836111, 33.149444],
   [-15.301667, 31.300833],
   [-15.850278, 30.433889],
   [-16.372778, 29.591389],
   [-16.604167, 28.033056],
   [-16.604167, 28.033056],
   [-16.604167, 28.033056],
   [-16.604167, 28.033056],
   [-16.604167, 28.033056],
   [-16.604167, 28.033056],
   [-16.604167, 28.033056],
   [-16.604167, 28.033056],
   [-17.452222, 28.4325],
   [-16.604167, 28.033056],
   [-16.604167, 28.033056],
   [-16.604167, 28.033056],
   [-17.170556, 28.274722],
   [-16.604167, 28.033056],
   [-16.604167, 28.033056],
   [-16.877222, 28.061389],
   [-16.604167, 28.033056],
   [-16.687778, 28.0025],
   [-16.604167, 28.033056],
   [-16.604167, 28.033056],
   [-16.604167, 28.033056],
   [-16.604167, 28.033056],
   [-16.5725, 28.044444]],
  'properties': {'times': [1459437925.0,
    1459437936.0,
    1459437977.0,
    1459438001.0,
    1459438032.0,
    1459438052.0,
    1459438128.0,
    1459438323.0,
    1459438339.0,
    1459438379.0,
    1459438422.0,
    1459438437.0,
    1459438468.0,
    1459438526.0,
    1459438550.0,
    1459438574.0,
    1459438620.0,
    1459438634.0,
    1459438672.0,
    1459438701.0,
    1459438758.0,
    1459438776.0,
    1459438863.0,
    1459438968.0,
    1459439065.0,
    1459439100.0,
    1459439203.0,
    1459439311.0,
    1459439382.0,
    1459439413.0,
    1459439716.0,
    1459439869.0,
    1459439940.0,
    1459440058.0,
    1459440321.0,
    1459440561.0,
    1459441465.0,
    1459441538.0,
    1459441643.0,
    1459442965.0,
    1459443070.0,
    1459443223.0,
    1459444370.0,
    1459445725.0,
    1459446654.0,
    1459447255.0,
    1459448245.0,
    1459448698.0,
    1459449135.0,
    1459449526.0,
    1459449549.0,
    1459449595.0,
    1459449674.0,
    1459449710.0,
    1459449746.0,
    1459449783.0,
    1459449832.0,
    1459449840.0,
    1459449882.0,
    1459449933.0,
    1459449985.0,
    1459450001.0,
    1459450038.0,
    1459450093.0,
    1459450202.0,
    1459450265.0,
    1459450325.0,
    1459450359.0,
    1459450457.0,
    1459450554.0,
    1459450621.0,
    1459450820.0]},
  'type': 'LineString'},
 'type': 'Feature'}

Lets show these coordinates as a trajectory in a map.

In [222]:
from folium.plugins import TimestampedGeoJson

map2 = folium.Map(location=[40,10], zoom_start=4, control_scale=True, prefer_canvas=True)
#tgj = TimestampedGeoJson(data = ng2, period = 'PT1M')
#map2.add_child(tgj, name='sometimestampedgeojson')


c = folium.GeoJson(ng2, name = 'Traj with time',overlay=True, 
                       style_function = lambda feature: {'fillColor': '#ffaf00','color': 'blue', 'weight': 2.5,'dashArray': '5, 5'},
                       highlight_function = lambda feature: {'fillColor': '#ffaf00','color': 'green', 'weight': 5,'dashArray': '5, 5'})
c.add_child(folium.Popup('some popup'))
c.add_to(map2)
folium.LayerControl().add_to(map2)
map2.save(outfile='maps/map2.html')

map2

In [223]:



#Convert WKT column into a gejson column
df["geojson"] = df["geom"].apply(lambda x: json.dumps(wkt.loads(x)))
df = df.drop('geom', 1)
df.head(3)

po = json.loads(singletraj.iloc[0]['geojson'])

print(po)
po['coordinates'] = [po['coordinates'][0], po['coordinates'][1], singletraj.iloc[0]['time'] ]
print(po)
type(po)

KeyError: 'geom'

In [311]:

qry = """ 
PREFIX : <http://www.datacron-project.eu/datAcron#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>

SELECT * WHERE {
    :n_AA51114077_20160401003000_1 ?p ?o .
}
"""

#to query another endpoint, change the URL for the service and the query
node = ts107.query(qry)
ts107.clean(st)
node.to_csv("node.csv")
node.head(10)

,o,p
0,http://www.datacron-project.eu/datAcron#t_1459...,http://www.ontologydesignpatterns.org/ont/dul/...
1,http://www.datacron-project.eu/datAcron#geom_LFMT,http://www.ontologydesignpatterns.org/ont/dul/...
2,http://www.datacron-project.eu/datAcron#n_AA51...,http://www.datacron-project.eu/datAcron#precedes

TODO / PROBLEM

Why is there no weather or no altitude attached?

# Intersecting areas and trajectories (Page 5)

In [26]:
qry = """ 
PREFIX : <http://www.datacron-project.eu/datAcron#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>

SELECT ?vessel ?time ?wkt ?speed ?event ?weather 
WHERE {
    ?s1 a :Node ;
          :ofMovingObject ?vessel ;
          :hasSpeed ?speed ;
        dul:hasConstituent/:TimeStart ?time ;
        dul:hasConstituent/:hasWKT ?wkt .
FILTER(bif:st_distance( bif:st_geomfromtext ("POINT(13.139045 44.466133)"), bif:st_geomfromtext(?wkt)) <= 5 &&
    xsd:dateTime(substr(?time,1,19))<xsd:dateTime("2016-01-08 16:12:41") && 
    xsd:dateTime(substr(?time,1,19))>xsd:dateTime("2016-01-08 14:12:41"))
}
"""

#to query another endpoint, change the URL for the service and the query
ci = ts107.query(qry)
ts107.clean(ci)
ci.to_csv("closeins.csv")
ci.head(10)

EndPointInternalError: EndPointInternalError: endpoint returned code 500 and response.

Response:
b'Virtuoso S1T00 Error SR171: Transaction timed out\n\nSPARQL query:\ndefine sql:big-data-const 0 \n#output-format:application/sparql-results+json\n \nPREFIX : <http://www.datacron-project.eu/datAcron#>\nPREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>\n\nSELECT ?vessel ?time ?wkt ?speed ?event ?weather \nWHERE {\n    ?s1 a :Node ;\n          :ofMovingObject ?vessel ;\n          :hasSpeed ?speed ;\n        dul:hasConstituent/:TimeStart ?time ;\n        dul:hasConstituent/:hasWKT ?wkt .\nFILTER(bif:st_distance( bif:st_geomfromtext ("POINT(13.139045 44.466133)"), bif:st_geomfromtext(?wkt)) <= 5 &&\n    xsd:dateTime(substr(?time,1,19))<xsd:dateTime("2016-01-08 16:12:41") && \n    xsd:dateTime(substr(?time,1,19))>xsd:dateTime("2016-01-08 14:12:41"))\n}\n'

PROBLEM

In the query above, taken directly from the tutorial, I receive a timeout on a sample query! What could be the problem here?

# Regulations rausziehen

This chapter is still under construction.


Regulations leben in einem Zeitintervall. Wenn wir also Regulations rausziehen wollen, so müssen wir immer angeben, welches Zeitintervall abgedeckt werden soll. Hierzu muss ein Startdatum $t_s$, ein Enddatum $t_e$ und die Intervallgröße $\Delta t$ angegeben werden. Die Anzahl der Timesteps ergibt sich dann als $$n = \frac{t_e - t_s}{\Delta t}$$
Es folgt: der $i-$te Zeitraum ist der, der bei $t_s + i \cdot \Delta t$ beginnt.

Wir beginnne mit einem Beispiel für den Airspace Airspace_LTBA_411, weil dieser sehr oft reguliert wird.

In [9]:
qry = """
PREFIX : <http://www.datacron-project.eu/datAcron#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>

SELECT ?s
WHERE {
  ?s rdfs:subClassOf* :FM_Regulation .
}
"""
 #?s rdf:type/rdfs:subClassOf* :SpatiotemporalRegion 

df = ts107.query(qry)
df = ts107.clean(df)
df.head(10)

                                               s
0                                  FM_Regulation
1                 ATC_WeatherAlternateRegulation
2                         ATC_SecurityRegulation
3  ATC_RestrictionWeatherAtDestinationRegulation
4         ATC_RestrictionStaffShortageRegulation
5                      ATC_RestrictionRegulation
6         ATC_RestrictionAtDestinationRegulation
7           ATC_RestrictionAtDepartureRegulation
8               ATC_OtherRegulationAtDestination
9         ATC_ImmigrationCustomsHealthRegulation

In [14]:
qry = """
PREFIX : <http://www.datacron-project.eu/datAcron#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>

SELECT ?s ?p ?o
WHERE {
  ?s a :ATC_WeatherRegulation ;
     ?p ?o
}
"""
 #?s rdf:type/rdfs:subClassOf* :SpatiotemporalRegion 

df = ts107.query(qry)
df = ts107.clean(df)
df.head(10)

df.to_csv('data/wxregulations.csv')

In [17]:
qry = """
PREFIX : <http://www.datacron-project.eu/datAcron#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>

SELECT ?p ?o
WHERE {
  :EDDFA01_411 ?p ?o
}
"""
 #?s rdf:type/rdfs:subClassOf* :SpatiotemporalRegion 

df = ts107.query(qry)
df = ts107.clean(df)
df.head(20)

                       p                                 o
0                   type             ATC_WeatherRegulation
1   RegulationAiracCycle                               411
2  RegulationDescription                      STRONG WINDS
3              hasRegion                   Sector_EDGGFMP1
4         hasParticipant                          ATC_EDDF
5        hasTimeInterval  intv_1459485600000_1459485600000

In [18]:
qry = """
PREFIX : <http://www.datacron-project.eu/datAcron#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>

SELECT ?p ?o
WHERE {
  :intv_1459485600000_1459485600000 ?p ?o
}
"""
 #?s rdf:type/rdfs:subClassOf* :SpatiotemporalRegion 

df = ts107.query(qry)
df = ts107.clean(df)
df.head(20)

           p                    o
0  TimeStart  2016-04-01T04:40:00
1    TimeEnd  2016-04-01T04:40:00
2   duration                   72

In [11]:
qry = """ 
PREFIX : <http://www.datacron-project.eu/datAcron#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX myfn: <java:datAcronTester.unipi.gr.sparql_functions.>

SELECT (count (DISTINCT ?regulation) as ?count)
WHERE {?regulation rdf:type/rdfs:subClassOf* :FM_Regulation ;
                   dul:hasRegion 'Airspace_LTBA_411' ;
                   dul:hasTimeInterval '6' .
       ?t :TimeStart ?s ;
          :TimeEnd   ?e .
FILTER(myfn:overlaps(?s, ?e, '2016-04-01 00:00:00'^^<http://www.w3.org/2001/XMLSchema#DateTime>, 
                             '2016-05-02 23:59:59'^^<http://www.w3.org/2001/XMLSchema#DateTime>))
}
"""

df = ts107.query(qry)
ts107.clean(df)
#df.to_csv("airspaceconfigs.csv")
#df = df[df.p != "#type"]
df.head(20)

  count
0     0

In [424]:
import cesiumpy

v = cesiumpy.Viewer()
b = cesiumpy.Box(dimensions=(40e4, 30e4, 50e4), material=cesiumpy.color.RED, position=[-120, 40, 0])
v.entities.add(b)

v

In [234]:
qry = """ 
PREFIX : <http://www.datacron-project.eu/datAcron#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX myfn: <java:datAcronTester.unipi.gr.sparql_functions.>

SELECT ?s ?w
WHERE {?s rdf:type :Node ;
          :hasWeatherCondition ?w .
} LIMIT 1000
"""




df = ts107.query(qry)
ts107.clean(df)
df.to_csv("data/someweather.csv")
#df = df[df.p != "#type"]
df.head(20)

,s,w
0,node_0_1453961518000_15.896575_43.7204233333333,weather_43.7204233333333_15.896575_0.0_1453971600
1,node_100000001_1453961006000_3.05081333333333_...,weather_36.7109833333333_3.05081333333333_0.0_...
2,node_104938_1453961970000_2.35546_51.042906666...,weather_51.0429066666667_2.35546_0.0_1453971600
3,node_10772765_1453961146000_4.71531666666667_5...,weather_51.828_4.71531666666667_0.0_1453971600
4,node_10772765_1453961746000_4.71518833333333_5...,weather_51.8279616666667_4.71518833333333_0.0_...
5,node_10772765_1453962107000_4.715225_51.827995,weather_51.827995_4.715225_0.0_1453971600
6,node_10878978_1453962062000_4.14806_51.9494466...,weather_51.9494466666667_4.14806_0.0_1453971600
7,node_10878978_1453962150000_4.14803333333333_5...,weather_51.9494333333333_4.14803333333333_0.0_...
8,node_11111111_1453961058000_-5.48814333333333_...,weather_35.8987816666667_-5.48814333333333_0.0...
9,node_11603_1453960418000_-3.03189_43.346333333...,weather_43.3463333333333_-3.03189_0.0_1453950000
10,node_11603_1453961406000_-3.03188666666667_43....,weather_43.3463316666667_-3.03188666666667_0.0...
11,node_118855500_1453960414000_5.61107_43.170305,weather_43.170305_5.61107_0.0_1453950000
12,node_12063_1453961850000_-3.09056333333333_43....,weather_43.3916366666667_-3.09056333333333_0.0...
13,node_123456790_1453961470000_2.62886333333333_...,weather_39.5610433333333_2.62886333333333_0.0_...
14,node_123456790_1453961834000_2.628885_39.56106...,weather_39.5610616666667_2.628885_0.0_1453971600
15,node_1605312_1453961774000_6.77598_51.457745,weather_51.457745_6.77598_0.0_1453971600
16,node_17739082_1453960539000_4.450655_51.880781...,weather_51.8807816666667_4.450655_0.0_1453950000
17,node_17739082_1453960978000_4.45059166666667_5...,weather_51.8808166666667_4.45059166666667_0.0_...
18,node_1774838_1453960862000_3.984325_51.4387566...,weather_51.4387566666667_3.984325_0.0_1453971600
19,node_1_1453960926000_15.0073216666667_42.003185,weather_42.003185_15.0073216666667_0.0_1453971600

In [238]:
qry = """ 
PREFIX : <http://www.datacron-project.eu/datAcron#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX myfn: <java:datAcronTester.unipi.gr.sparql_functions.>

SELECT DISTINCT ?p ?o
WHERE {:weather_43.7204233333333_15.896575_0.0_1453971600  ?p        ?o .
} LIMIT 1000
"""




df = ts107.query(qry)
ts107.clean(df)
df.to_csv("data/someweather_condition.csv")
#df = df[df.p != "#type"]
df.head(20)

                        p                 o
0                    type  WeatherCondition
1        reportedDewPoint         14.859985
2  reportedMaxTemperature         14.799988
3  reportedMinTemperature         14.799988
4        reportedPressure         101688.46
5        windDirectionMax         250.32214
6        windDirectionMin         250.32214
7            windSpeedMax          1.603652
8            windSpeedMin          1.603652

In [239]:
qry = """ 
PREFIX : <http://www.datacron-project.eu/datAcron#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX myfn: <java:datAcronTester.unipi.gr.sparql_functions.>

SELECT DISTINCT ?p
WHERE {?s rdf:type :WeatherCondition ; 
          ?p        ?o .
} LIMIT 1000
"""




df = ts107.query(qry)
ts107.clean(df)
df.to_csv("data/someweather_condition.csv")
#df = df[df.p != "#type"]
df.head(20)

                        p
0                    type
1        reportedDewPoint
2  reportedMaxTemperature
3  reportedMinTemperature
4        reportedPressure
5        windDirectionMax
6        windDirectionMin
7            windSpeedMax
8            windSpeedMin

In [240]:
qry = """ 
PREFIX : <http://www.datacron-project.eu/datAcron#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX myfn: <java:datAcronTester.unipi.gr.sparql_functions.>

SELECT ?s ?w ?windspeedmax
WHERE {?s rdf:type :Node ;
          :hasWeatherCondition ?w .
       ?w :windSpeedMax ?windspeedmax   
} LIMIT 1000
"""




df = ts107.query(qry)
ts107.clean(df)
df.to_csv("data/someweather.csv")
#df = df[df.p != "#type"]
df.head(20)

,s,w,windspeedmax
0,node_209283000_1453961175000_-9.67183333333333...,weather_30.4155_-9.67183333333333_0.0_1453971600,3.905125
1,node_209167000_1453960982000_33.0128883333333_...,weather_34.6450183333333_33.0128883333333_0.0_...,6.0817924
2,node_209167000_1453960618000_33.01285_34.64501,weather_34.64501_33.01285_0.0_1453950000,5.7729197
3,node_209167000_1453961698000_33.012855_34.6450...,weather_34.6450216666667_33.012855_0.0_1453971600,6.0817924
4,node_209645000_1453960922000_33.0074216666667_...,weather_34.647225_33.0074216666667_0.0_1453971600,6.0817924
5,node_209645000_1453961198000_33.0074216666667_...,weather_34.647225_33.0074216666667_0.0_1453971600,6.0817924
6,node_209259000_1453961386000_33.0071833333333_...,weather_34.647385_33.0071833333333_0.0_1453971600,6.0817924
7,node_209413000_1453961126000_33.0099466666667_...,weather_34.647925_33.0099466666667_0.0_1453971600,6.0817924
8,node_209413000_1453960411000_33.009935_34.647935,weather_34.647935_33.009935_0.0_1453950000,5.7729197
9,node_209413000_1453961847000_33.009915_34.6479...,weather_34.6479466666667_33.009915_0.0_1453971600,6.0817924
10,node_209352000_1453962174000_33.0296983333333_...,weather_34.6644233333333_33.0296983333333_0.0_...,6.0817924
11,node_209352000_1453961558000_33.0297116666667_...,weather_34.6644283333333_33.0297116666667_0.0_...,6.0817924
12,node_209232000_1453961482000_33.0433966666667_...,weather_34.6694166666667_33.0433966666667_0.0_...,6.0817924
13,node_209232000_1453960974000_33.0432833333333_...,weather_34.66941_33.0432833333333_0.0_1453971600,6.0817924
14,node_209353000_1453960646000_14.5017566666667_...,weather_35.880955_14.5017566666667_0.0_1453950000,6.471947
15,node_209353000_1453961626000_14.5017633333333_...,weather_35.8809583333333_14.5017633333333_0.0_...,5.9352674
16,node_11111111_1453961058000_-5.48814333333333_...,weather_35.8987816666667_-5.48814333333333_0.0...,5.8798385
17,node_209375000_1453960634000_-5.60326833333333...,weather_36.0101366666667_-5.60326833333333_0.0...,6.9609337
18,node_205871910_1453961550000_-4.61622666666667...,weather_36.5423233333333_-4.61622666666667_0.0...,7.1856594
19,node_100000001_1453961006000_3.05081333333333_...,weather_36.7109833333333_3.05081333333333_0.0_...,10.128777